Add workaround for https://github.com/npm/uid-number/issues/3
npm config set unsafe-perm true is called otherwise we get

    Error: could not get uid/gid
    [ 'nobody', 0 ]

    at .../uid-number/uid-number.js:37:16
    ...

error.